# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sq.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(501, 374)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 110, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(73, 205, 71, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(160, 270, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 270, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(Form.close)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(160, 109, 201, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 199, 201, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.lineEdit.textChanged.connect(lambda :self.on_edit_textChanged())

    def on_edit_textChanged(self):
        facename = self.lineEdit.text()
        print("...", facename)
        if len(facename)>7:#日期  格式为YYYYMMDD
            self.pushButton.clicked.connect(self.xiaoquyouhui(self.lineEdit.text()))

    def xiaoquyouhui(self,date):
        read_path = 'E:\\WORK\\优惠小区\\优惠小区导入' + date + '\\优惠小区导入' + date + '.xlsx'
        out_path = 'E:\\WORK\\优惠小区\\优惠小区导入' + date + '\\优惠小区导入' + date + '结果.xlsx'
        with pd.ExcelFile(read_path) as xls:
            df1 = pd.read_excel(xls, 'Sheet1')
            df2 = pd.read_excel(xls, 'Sheet2')

            df1['区县'] = df1['区县'].map(lambda 区县: 区县[0:2])
            df2['区县'] = df2['区县'].map(lambda 区县: 区县[0:2])

            print(df1['区县'])

        outer = pd.merge(df1, df2, on='区县')

        print(outer)

        outer.to_excel(out_path, index=False, encoding='utf-8')

        df3 = pd.read_excel(xls, 'Sheet3')

        print(df3)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "优惠小区"))
        self.label_2.setText(_translate("Form", "结果表"))
        self.pushButton.setText(_translate("Form", "OK"))
        self.pushButton_2.setText(_translate("Form", "CANCEL"))






if __name__=="__main__":
    import sys
    app=QtWidgets.QApplication(sys.argv)
    widget=QtWidgets.QWidget()
    ui=Ui_Form()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())